name: DuelPlugin
version: ${project.version}
main: me.winiecki.DuelPlugin
api-version: 1.13
commands:
  duel:
    description: 'challenge a player to a duel'
    usage: /<command>
  duelstats:
    description: 'check your all-time Duel stats'
    usage: /<command>